### PR TITLE
Add ensime

### PR DESCRIPTION
**Pull request by benjaminfrank**
Not sure if you want the order to be project `ensime` or var `user-emacs-ensime-directory`

### CODE REVIEW

**Comment by justbur** [comment]
Not sure either ;). Let's see what @tarsius thinks.

**Comment by tarsius** [comment]
Order by variable name for now (we can still change it later if we have to add other ensime variables).

**Comment by benjaminfrank** [comment]
Changed order accordingly.

**Comment by justbur** [comment]
Thanks!

**Pull request merged**
