### PR TITLE
Added a bunch of builtin and 3rd party package files used by me

### PR DESCRIPTION
**Pull request by wiedzmin**

### CODE REVIEW

**Comment by justbur** [comment]
Thanks can you follow the ordering conventions and sort these?

**Comment by wiedzmin** [comment]
Am I right you mean only lack of alphabetical order? I've reread conventions list and have found only this (my fault :-[ ).

**Comment by wiedzmin** [comment]
BTW "ensime" entry from tarsius/no-littering@0b8f2f also seems to be out of sort (if I'm not mistaken). Should I fix it too?

**Comment by justbur** [comment]
> BTW "ensime" entry from tarsius/no-littering@0b8f2fa also seems to be out of sort (if I'm not mistaken). Should I fix it too?

The sorting is on variable name for now. I clarified this just now in the readme.

**Comment by justbur** [comment]
> Am I right you mean only lack of alphabetical order? 

Yes alphabetical

**Comment by wiedzmin** [comment]
Done.

**Comment by justbur** [comment]
Thank you. I made a couple of tweaks.

**Pull request merged**
