### PR TITLE
tldr: theme tldr-directory-path

### PR DESCRIPTION
**Pull request by therockmandolinist**

### CODE REVIEW

**Comment by tarsius** [comment]
```lisp
(defvar tldr-pages-dir (concat tldr-directory-path "pages/")
  "Don't change me you idiot!")
```

Despite the insult, this variable actually has to be set. Also it should be defined using `defcustom` and the definition should contain `:set-after '(tldr-directory-path)`. Or better yet, this variable should be removed completely. Please discuss this with upstream.

**Comment by tarsius** [comment]
[tldr](https://github.com/kuanyui/tldr.el)

/cc @kuanyui

**Comment by kuanyui** [comment]
Sorry for the insult, I did never assume that docstring will be read. 😅 
However, I don't understand what this project exactly is doing....@@

**Comment by therockmandolinist** [comment]
@tarsius I'm not sure I understand - won't the pages dir just be placed wherever tldr-directory-path? And what would be the advantage of removing it (not that I see why it's necessary either, just wondering)?

**Comment by tarsius** [comment]
Applied because the mentioned issue does not actually affect `no-littering` because `no-littering` should be loaded before the packages it modifies, so https://github.com/kuanyui/tldr.el/pull/21 has no effect if users do things as instructed.

But that issue should still be fixed for non-no-littering users.

**Pull request closed without merging**
