### PR TITLE
company-statistics: theme company-statistics-file

### PR DESCRIPTION
**Pull request by swarnendubiswas**
Added a configuration for company-statistics-file.

### CODE REVIEW

**Comment by tarsius** [comment]
We keep these lists sorted alphabetically, so please move your addition to the correct place. Also please use `(var "company/statistics.el")`.

**Comment by swarnendubiswas** [comment]
I will do that, but shouldn't we name the file `company/statistics-cache.el`?

**Comment by justbur** [comment]
Thanks!

**Comment by justbur** [comment]
In most cases I think "cache" is analogous to "file", so to fit the conventions it makes sense to drop it.

**Pull request merged**
