### PR TITLE
Add persistent-scratch

### PR DESCRIPTION
**Pull request by benjaminfrank**

### CODE REVIEW

**Comment by benjaminfrank** [comment]
persistent-scratch also has `persistent-scratch-backup-directory` but semantics is to keep backups once the folder is non-nil. I think setting this as default might not what a user expects and thus omited it in this PR.

**Comment by justbur** [comment]
Thanks, but we're trying to keep the variables for third-party packages in alphabetical order.

**Comment by justbur** [comment]
> persistent-scratch also has persistent-scratch-backup-directory but semantics is to keep backups once the folder is non-nil. I think setting this as default might not what a user expects and thus omited it in this PR.

Yes, that's not something we would want to choose for them I don't think.

**Comment by benjaminfrank** [comment]
Changed order.

**Comment by justbur** [comment]
Looks good. Thanks

**Pull request merged**
